application: sage-outrider-373
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
  - url: /static/js/custom.js
  static_files: static/js/custom.js
  upload: static/js/custom.js

 
- url: /.*
  script: simplegallery.application
  

  

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest